# Use the official Ubuntu 20.04 as the base image
FROM mcr.microsoft.com/devcontainers/base:bookworm

# Install any additional dependencies here
RUN apt-get update && apt-get install -y \
    build-essential \
    ruby-full \
    ruby-bundler \
    zlib1g-dev




